name: Multi Repository Sync
description: Sync multiple files from source repository to multiple targets using PRs.

branding:
  color: black
  icon: git-pull-request

inputs:
  github_token:
    description: The GitHub token to use
    required: true

  config_path:
    description: Path to config file
    default: .github/multi-repo-sync-config.json
    required: false

  dry_run:
    description: Only show output, don't apply syncs or creates PRs
    default: "false"
    required: false

runs:
  # TODO: This should probably be containerized
  using: composite
  steps:
    - run: cd ${{ github.action_path }} && uv sync
      shell: bash
    - run: cd ${{ github.action_path }} && uv run app.py
      env:
        MRS_GITHUB_TOKEN: ${{ inputs.github_token }}
        MRS_CONFIG_PATH: ${{ inputs.config_path }}
        MRS_DRY_RUN: ${{ inputs.dry_run }}
      shell: bash
