[project]
name = "multi-repo-sync-action"
version = "0.0.1"
description = "The multi-repo-sync GitHub action code base - Sync multiple files from source repository to multiple targets using PRs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "pygithub>=2.8.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.3",
]

[tool.ruff]
select = ["ALL"]
ignore = [
    "T201",  # Allow print statements (TODO: Remove once logger is added)
    "RET504",  # Allow redundant assignment before return for readability
    "D",  # Docs related rules
    "PTH123",  # Allow regular open
    "PLR2004",  # Allow hard-coded values in comparisons
    "SIM103",  # Allow useless if's for readability
    "TRY003",  # Allow literal strings in exception raises
    "EM101",  # Allow literal strings in exception raises
]
